### ISSUE TITLE
Collisions with boundaries

### ISSUE THREAD

**Issue by mashkoff** [mashkoff/gravity#3]
Collision with a boundary should cause a perfectly elastic impact (рус. абсолютно упругий удар)

**Comment by mashkoff** [comment]
Implementation has to be these way: width and height of the frame are stored in global variables and can be accessed by Agents to check for the collisions in update() method

Also radius divisor should be stored globally to be accessible in update() either

**Comment by orchaton** [comment]
We've got Globals.py which has dictionary objects_data, which has field objects_data["widget_width"] and objects_data["widget_height"]. This module should be importred in this way: from utils import Globals. And then use "super-global" list Globals.objects_data[]

**Comment by mashkoff** [comment]
The feature has been implemented.
